### PR TITLE
Theme update: Remove 'en/' from OMS docs link in site switcher

### PR DESCRIPTION
**Pull request by belbiy**
- Remove 'en/' from OMS docs link in site switcher
- Some small theme tweaks to improve styling and general maintenance and cleanup

### CODE REVIEW

**Comment by dshevtsov** [comment]
@belbiy could you please also fix the 'link to a title' feature that helped to get rid of redundant url parameters after a page was find via the devdocs search?

**Comment by belbiy** [comment]
@dshevtsov , that's a pretty big feature actually. Requires a new script to be added to the theme in order to add the anchor to h1. Since currently the heading anchors are generated from Jekyll TOC. There's no anchor for h1 because it's not part of TOC

**Comment by dshevtsov** [comment]
I remember that we have already had this feature implemented already, but at some moment it stopped working. I thought, it might be a bug that could be fixed with little effort.

**Comment by belbiy** [comment]
If at one point our h1 was coming from markdown, like this:

```
# Page title
```

then yes, it might have worked like that. The anchors are basically generated from markdown titles.
To add an anchor to h1, i need to build a new script that:

1. Reads the browser URL bar and cleans it out of all the junk.
2. Appends the `<a>` tag to h1 so the icon gets displayed.

It's not a lot of work, but not something i have time for now.

**Comment by belbiy** [comment]
@shrielenee @danidelcar or @jeff-matthews  - can any of you approve the changes? This is just to remove that `en` part from the URL to OMS docs.

**Review by jeff-matthews — APPROVED** [review]

**Pull request merged**
