### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dshevtsov**
Updating dependencies to resolve the vulnerabilities reported by Dependabot.
Also, adding browser-sync to dependencies, which was missing.

(For internal contributors, see DOC-574 for details and previews.)

## Update

Adding `spectrum-Tabs--sizeM` class to the `src/_includes/layout/navigation.html` because `spectrum-Tabs--size*` is now mandatory.

> Tabs now support t-shirt sizing and require that you specify the size by adding a .spectrum-Tabs--size* class.
https://opensource.adobe.com/spectrum-css/tabs.html#migrationguide

### CODE REVIEW

**Comment by dshevtsov** [comment]
@bdenham there is an issue with the top navigation. Is it a known issue? How do I fix that?
Screen Shot 2022-02-01 at 11 58 43 AM

**Review by bdenham — APPROVED** [review]
All looks good!

image

**Comment by bdenham** [comment]
Let me take a quick peek at the top navigation.

**Comment by bdenham** [comment]
Yeah, top navigation is definitely messed up. This makes me wonder how much is messed up elsewhere. Previous version shown here: 
image

**Comment by bdenham** [comment]
@dshevtsov and @dobooth Checkout out updates to the Tabs or list items and other CSS in the `nav-main` area.
 
image

**Comment by bdenham** [comment]
This shows the area and the start of where I would apply fixes. But be diligent in determining what the margin or padding spacing was before the update and other areas that may have changed. 

image

**Review by bdenham — CHANGES_REQUESTED** [review]
You will need to fix the nav-main area and then do some testing against devdocs to make sure nothing else has changed.

**Comment by dshevtsov** [comment]
`master` doesn't have this issue.
I assume that some changes were made in https://github.com/magento-devdocs/devdocs-theme/pull/98 but they were not compiled with `build:css`.

**Comment by dshevtsov** [comment]
> I assume that some changes were made in #98 but they were not compiled with build:CSS.

Confirmed. The issue was present on `master`. When I build CSS on `master`, the issue appears there too.

**Comment by dshevtsov** [comment]
The issue appears even earlier, in #93

**Comment by dshevtsov** [comment]
@bdenham, it seems like the top navigation has been broken since #74

**Comment by dshevtsov** [comment]
The bug was introduced in 0a753f5.

**Comment by dshevtsov** [comment]
Well, the bug was in my way of debugging. I didn't reinstall dependencies when I tried to rebuild older commits. The navigation is broken since 2ee0c3f when I upgraded all the npm dependencies, including the Spectrum dependencies. I misunderstood _[Spectrum updates](https://github.com/magento-devdocs/devdocs-theme/pull/100#issuecomment-1027281450)_.

**Comment by dshevtsov** [comment]
> Tabs now support t-shirt sizing and require that you specify the size by adding a .spectrum-Tabs--size* class.

Looks like this is the issue.

**Comment by dshevtsov** [comment]
It appears that `src/_includes/layout/navigation.html` also needs to be updated in each doc project separately.

**Comment by dshevtsov** [comment]
I updated the projects, which fixed the issue. (For internal contributors, see DOC-574 for details.)

**Comment by dshevtsov** [comment]
I'm creating internal PRs to prepare for the theme update.

**Comment by dshevtsov** [comment]
The separator is missing on [production](https://devdocs.magento.com/), so I won't dig into it in this PR. @bdenham please open an issue for the separator issue.

**Comment by dshevtsov** [comment]
@bdenham I suggest merging the `src/_includes/layout/navigation.html` fix along with the theme updates in the docs projects.

**Comment by dshevtsov** [comment]
I mean the following:
1. We merge this PR. It won't be applied until we update the reference in the `Gemfile.lock`
1. I create PRs in devdocs, mecrhdocs, etc where I update `src/_includes/layout/navigation.html` and update the theme reference in `Gemfile.lock`.

Otherwise, the update would require more PRs:
1. PRs to doc projects to update `src/_includes/layout/navigation.html`
1. Merge this PR
1. PRs to doc projects to update the theme reference in `Gemfile.lock`

**Review by bdenham — APPROVED** [review]
Looks great! Nice job!

image

**Pull request merged**
