### PR TITLE
Update the merchdocs index and site url

### PR DESCRIPTION
**Pull request by belbiy**
1. Changes the app switcher URL to use the new user-guide address.
2. Updates the federated search with new index (has to be done on all the websites)

NOTE:  It’s basically a template for updating all the websites with new URL.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
This isn't within the scope of this PR, but why is the `user-guide` piece of the URL necessary?

**Comment by belbiy** [comment]
@jeff-matthews, this is essentially a base url for the results from that website. Or you asking why do we need `user-guide` for merchant docs at all, and should use the root of docs.magento.com?

**Comment by jeff-matthews** [comment]
@belbiy, this:

> why do we need `user-guide` for merchant docs at all, and should use the root of docs.magento.com?

it seems unnecessary

**Comment by belbiy** [comment]
I agree from the user perspective, it makes sense. It's a user guide for Magento. 

But from our internal deployment perspective that I think was too risky, to get rid of `user-guide` as an enclosing folder for the `merchdocs` repo output. I dont fully understand the build logic, but there's other repos like `merchdocs-mbi` that can be affected (or not). But let's continue that converstation in Slack and possibly revisit that.

**Pull request merged**
