### PR TITLE
Theme fixes

### PR DESCRIPTION
**Pull request by bdenham**
## Description

This PR fixes the following theme issues:
- #84 
- #85 
- #86 
- #87 

This PR also incorporates PR #60 Add flag icon for md usage in lists.

## Staged Builds to verify updates

- MerchDocs: https://docs.magedevteam.com/182/user-guide/
- DevDocs: https://devdocs.magedevteam.com/357/ — No known issues with devdocs to verify. Just make a simple sweep, a "visual smoke test" to verify nothing regressed on devdocs.

### CODE REVIEW

**Comment by leslietilling** [comment]
@bdenham  I thought this was covered by #85, but staging still shows missing icon in "cards" : 
image

**Review by dshevtsov — COMMENTED** [review]
Confirming fix of #84

**Review by belbiy — APPROVED** [review]
Looks good, thank you for the hard work!

**Comment by bdenham** [comment]
@dshevtsov, as a side project, I'll continue to research more on the scss linting. I think I'm close, I just need to find the magic configuration and location of files within linters and workflows directories.

**Comment by dshevtsov** [comment]
Sounds good, thanks!
@leslietilling can you confirm that the issue you reported was fixed?

**Comment by bdenham** [comment]
> @bdenham I thought this was covered by #85, but staging still shows missing icon in "cards" :
> image

@leslietilling Fixed: 
image

**Comment by bdenham** [comment]
Per @leslietilling's finding that the github links (edit and issue) on each page were no longer using target="_blank" since I converted those anchor links to buttons in my first pass 3 months ago. This last fix changes those links from buttons back to anchor links.

**Review by leslietilling — APPROVED** [review]

**Comment by dshevtsov** [comment]
@bdenham, have you checked how this update will impact other projects: oms-docs, merchdocs-mbi, pwa?

**Pull request merged**
