### PR TITLE
Fix theme after updating Spectrum dependencies

### PR DESCRIPTION
**Pull request by dshevtsov**
PR #100 introduced Spectrum updates with breaking changes.

This PR fixes tables, alerts, and tutorial buttons.
Also:
- adding the tutorial layout and an example tutorial to the theme,
- disabling the standardjs linter because I'm not aware of best practices how to resolve the cases when an entity is declared dynamically, and the linter is not configurable; the JS files are still covered by the eslint linter.

Internal ticket: DOC-574

### CODE REVIEW

**Review by bdenham — CHANGES_REQUESTED** [review]
Found another horizontal list that requires a similar fix as the nav header menu.

image

**Comment by dshevtsov** [comment]
@bdenham, fixed.

**Comment by bdenham** [comment]
Looks good! There's only one more area to check to make sure our theme CSS isn't responsible for this difference:

image

image

**Review by bdenham — APPROVED** [review]
See comment. Just check to see if it's Spectrum-only.

**Comment by dshevtsov** [comment]
Thanks, @bdenham.
This PR doesn't contain any direct CSS changes. It's only resolving breaking changes caused by Spectrum. I'll check if this is another breaking change.

**Review by bdenham — APPROVED** [review]
Couldn't find anything else (and I looked at every area I could think of.) Ship it! :)

**Pull request merged**
