### PR TITLE
[DOC-299] Rebranding theme with latest Spectrum CSS and branding content

### PR DESCRIPTION
**Pull request by bdenham**
This PR updates all Spectrum CSS packages and adds new ones to the devdocs theme. Many changes were made and much testing has been done to fix the issues created by new Spectrum styling.

I will make another few passes with more staging builds to catch all the obvious CSS abberations. After I'm done, I'll mark it as ready for review.

More soon...

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
Quite a bit going on here... Is there a staging build for devdocs that I can look at?

**Comment by bdenham** [comment]
Yes. A lot. And no, not yet. I hope to get one out there later today. I used merchdocs as my testbed for all these changes, fixing CSS aberrations as I went. There are still a few that I will address after I finish the devdocs content changes.

**Comment by belbiy** [comment]
I think it's better to use `quiet` buttons on the github links block, these ones look way off, never seen that on other adobe products. I know it's technically allowed, just saying it looks "off" ;-)
Screen Shot 2021-05-18 at 7 56 11 PM

**Comment by jeff-matthews** [comment]
The version switcher button also looks off:

Screen Shot 2021-05-19 at 7 43 16 AM

And the search bar needs some alignment:

Screen Shot 2021-05-19 at 7 45 02 AM

**Review by jeff-matthews — APPROVED** [review]
Latest devdocs staging build looks good!

https://devdocs.magedevteam.com/261/

**Comment by belbiy** [comment]
Couple of small bugs:

Github link still look a little bit off:
Screen Shot 2021-05-20 at 11 35 15 AM
You probably need to add a `spectrum-ActionButton` class to the `button` itself. Also make sure that you adding `spectrum-ActionButton--sizeM` (or sizeS) to both button and icon (spectrum-Icon--sizeM). This is a new syntax i think, it makes code more verbose, but also makes buttons look more consistent.

Kind of same thing with the page updated button:
Screen Shot 2021-05-20 at 11 37 22 AM
`button` needs a size class `spectrum-ActionButton--sizeM` and icon should have the corresponging  `spectrum-Icon--sizeM`

Other than that, looks great!

**Comment by bdenham** [comment]
Thanks for the sanity check, Eugene! Got em.

**Review by jeff-matthews — APPROVED** [review]

**Review by jeff-matthews — APPROVED** [review]

**Pull request merged**
